### ISSUE TITLE
'There was a problem starting GetKeyboardLayout.dll'

### ISSUE THREAD

**Issue by Dave3848** [Saya47/GetKeyboardLayout#1]
I get:

```
---------------------------
RunDLL
---------------------------
There was a problem starting GetKeyboardLayout.dll

The specified module could not be found.


---------------------------
OK   
---------------------------

```

Upon running 'Example-AHK_L.ahk'. It is inside, together with the rest of the files...

**Comment by Saya47** [comment]
@Dave3848 Only the source files were uploaded here, to get the dll you should compile the source code, but for your convenience, I created a release so you can just use the dll file I compiled:

https://github.com/Saya47/GetKeyboardLayout/releases/tag/v.0.0.1

**Comment by Dave3848** [comment]
> @Dave3848 Only the source files were uploaded here, to get the dll you should compile the source code, but for your convenience, I created a release so you can just use the dll file I compiled:
> 
> https://github.com/Saya47/GetKeyboardLayout/releases/tag/v.0.0.1

That was sweet of you, thanks 👉👈
